function [map_polytopes,all_pts,mu_rad_final,sigma_rad_final] = ...
    fcn_MapGen_polytopeMapGen(...
    halton_range,...
    bounding_box,...
    des_radius,sigma_radius,min_rad,shrink_seed,varargin)
% fcn_MapGen_polytopeMapGen creates a polytope map generated by a Halton
% set polytopes, with given desired radius and standard deviation in
% radius.
%
% FORMAT:
%
% [map_polytopes,all_pts,mu_rad_final,sigma_rad_final] = ...
%     fcn_MapGen_polytopeMapGen(...
%     halton_range,...
%     bounding_box,...
%     des_radius,sigma_radius,min_rad,shrink_seed, (fig_num))
%
% INPUTS:
%
%    halton_range: 1 x 2 vector of integers specifying the [low high] range
%    of Halton points to use to generate the tiling
%
%    bounding_box: a 2 x 2 matrix of [xlow ylow; xhigh yhigh] in which all
%    the polytopes must exist, e.g. the corner coordinates of the
%    axis-aligned bounding box.
%
%    des_radius:
%
%    sigma_radius:
%
%    min_rad:
%
%    shrink_seed:
%
%    (OPTIONAL INPUTS)
%
%      fig_num: a figure number to plot results. If set to -1, skips any
%      input checking or debugging, no figures will be generated, and sets
%      up code to maximize speed. As well, if given, this forces the
%      variable types to be displayed as output and as well makes the input
%      check process verbose.
%
% OUTPUTS:
%
%     map_polytopes: an N x 2 matrix representing the [x y] vector of starting
%     points of the "walls", where N is # of wall segments
%
%     all_pts: an N x 2 matrix representing the [x y] vector of ending
%     points of the "walls", where N is # of wall segments
%
%     mu_rad_final:
%
%     sigma_rad_final
%
% DEPENDENCIES:
%
%      fcn_DebugTools_checkInputsToFunctions
%      fcn_MapGen_haltonVoronoiTiling
%      fcn_MapGen_polytopeCropEdges
%      fcn_MapGen_polytopesShrinkToRadius
%      fcn_MapGen_plotPolytopes
%
% EXAMPLES:
%
% See the script: script_test_fcn_MapGen_polytopeMapGen
% for a full test suite.
%
% This function was written on 2020_06_06 by S. Brennan by editing
% fcn_basic_polytope_map_generation written by S. Tau.
% Questions or comments? sbrennan@psu.edu

% REVISION HISTORY:
% 2021_06_06
% -- first written by S. Brennan.
% 2025_04_25 by Sean Brennan
% -- added global debugging options
% -- switched input checking to fcn_DebugTools_checkInputsToFunctions

% TO DO
% -- none

%% Debugging and Input checks

% Check if flag_max_speed set. This occurs if the fig_num variable input
% argument (varargin) is given a number of -1, which is not a valid figure
% number.
flag_max_speed = 0;
if (nargin==3 && isequal(varargin{end},-1))
    flag_do_debug = 0; % % % % Flag to plot the results for debugging
    flag_check_inputs = 0; % Flag to perform input checking
    flag_max_speed = 1;
else
    % Check to see if we are externally setting debug mode to be "on"
    flag_do_debug = 0; % % % % Flag to plot the results for debugging
    flag_check_inputs = 1; % Flag to perform input checking
    MATLABFLAG_MAPGEN_FLAG_CHECK_INPUTS = getenv("MATLABFLAG_MAPGEN_FLAG_CHECK_INPUTS");
    MATLABFLAG_MAPGEN_FLAG_DO_DEBUG = getenv("MATLABFLAG_MAPGEN_FLAG_DO_DEBUG");
    if ~isempty(MATLABFLAG_MAPGEN_FLAG_CHECK_INPUTS) && ~isempty(MATLABFLAG_MAPGEN_FLAG_DO_DEBUG)
        flag_do_debug = str2double(MATLABFLAG_MAPGEN_FLAG_DO_DEBUG);
        flag_check_inputs  = str2double(MATLABFLAG_MAPGEN_FLAG_CHECK_INPUTS);
    end
end

% flag_do_debug = 1;

if flag_do_debug
    st = dbstack; %#ok<*UNRCH>
    fprintf(1,'STARTING function: %s, in file: %s\n',st(1).name,st(1).file);
    debug_fig_num = 999978; %#ok<NASGU>
else
    debug_fig_num = []; %#ok<NASGU>
end


%% check input arguments?
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   _____                   _
%  |_   _|                 | |
%    | |  _ __  _ __  _   _| |_ ___
%    | | | '_ \| '_ \| | | | __/ __|
%   _| |_| | | | |_) | |_| | |_\__ \
%  |_____|_| |_| .__/ \__,_|\__|___/
%              | |
%              |_|
% See: http://patorjk.com/software/taag/#p=display&f=Big&t=Inputs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if (0==flag_max_speed)
    if flag_check_inputs
        % Are there the right number of inputs?
        narginchk(6,7);

        % Check the halton_range input
        fcn_DebugTools_checkInputsToFunctions(...
            halton_range, '2column_of_integers');

        % Check the bounding_box input
        fcn_DebugTools_checkInputsToFunctions(...
            bounding_box, '2column_of_numbers',2);

    end
end


% Does user want to show the plots?
flag_do_plot = 0; % Default is no plotting
if  7 == nargin && (0==flag_max_speed) % Only create a figure if NOT maximizing speed
    temp = varargin{end}; % Last argument is always figure number
    if ~isempty(temp) % Make sure the user is not giving empty input
        fig_num = temp;
        flag_do_plot = 1; % Set flag to do plotting
    end
else
    if flag_do_debug % If in debug mode, do plotting but to an arbitrary figure number
        fig = figure;
        fig_for_debug = fig.Number; %#ok<NASGU>
        flag_do_plot = 1;
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   __  __       _
%  |  \/  |     (_)
%  | \  / | __ _ _ _ __
%  | |\/| |/ _` | | '_ \
%  | |  | | (_| | | | | |
%  |_|  |_|\__,_|_|_| |_|
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% generate Voronoi tiling from Halton points
tiled_polytopes = fcn_MapGen_haltonVoronoiTiling(halton_range);

% remove the edge polytopes that extend past the high and low points
trimmed_polytopes = ...
    fcn_MapGen_polytopeCropEdges(tiled_polytopes,bounding_box);

% shink the polytopes so that they are no longer tiled
rng(shrink_seed) % set the random number generator with the shrink seed
[map_polytopes,mu_rad_final,sigma_rad_final] = ...
    fcn_MapGen_polytopesShrinkToRadius(trimmed_polytopes,...
    des_radius,sigma_radius,min_rad);

% gather data on all the points by looping through the polytopes
point_tot = length([map_polytopes.xv]); % total number of vertices in the polytopes
beg_end = zeros(1,point_tot); % is the point the start/end of an obstacle
curpt = 0;
for poly = 1:size(map_polytopes,2) % check each polytope
    verts = length(map_polytopes(poly).xv);
    map_polytopes(poly).obs_id = ones(1,verts)*poly; % obs_id is the same for every vertex on a single polytope
    beg_end([curpt+1,curpt+verts]) = 1; % the first and last vertices are marked with 1 and all others are 0
    curpt = curpt+verts;
end
obs_id = [map_polytopes.obs_id];
all_pts = [[map_polytopes.xv];[map_polytopes.yv];1:point_tot;obs_id;beg_end]'; % all points [x y point_id obs_id beg_end]

%% Plot results?
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   _____       _
%  |  __ \     | |
%  | |  | | ___| |__  _   _  __ _
%  | |  | |/ _ \ '_ \| | | |/ _` |
%  | |__| |  __/ |_) | |_| | (_| |
%  |_____/ \___|_.__/ \__,_|\__, |
%                            __/ |
%                           |___/
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if flag_do_plot
    figure(fig_num);
    hold on

    % plot the tiled_polytopes
    fcn_MapGen_plotPolytopes(tiled_polytopes,fig_num,'b',2,[0 1 0 1]);

    % plot the trimmed_polytopes
    fcn_MapGen_plotPolytopes(trimmed_polytopes,fig_num,'g',2,[0 1 0 1]);

    % plot the map_polytopes
    fcn_MapGen_plotPolytopes(map_polytopes,fig_num,'r',2,[0 1 0 1]);

end

if flag_do_debug
    fprintf(1,'ENDING function: %s, in file: %s\n\n',st(1).name,st(1).file);
end


end % Ends the function

