% script_test_fcn_MapGen_calculateConvexHullOverlapRatio
% Tests: fcn_MapGen_calculateConvexHullOverlapRatio

%
% REVISION HISTORY:
%
% 2024_02_28 by Steve Harnett
% -- first write of script
% 2025_04_16 by Steve Harnett
% -- remove dependence on test fixture
%%%%%%%%%%%%%%§

close all; clear all; clc;

%% basic polytope case
polytopes(1).vertices = [0 0; 10 0; 10 1; 0 1; 0 0];
polytopes(2).vertices = polytopes(1).vertices+[8,0];
polytopes = fcn_MapGen_fillPolytopeFieldsFromVertices(polytopes);
fig_num = 1;
[ ...
convex_hull_overlap_ratio,...
A_overlap,...
A_occupied...
] = ...
fcn_MapGen_calculateConvexHullOverlapRatio( ...
polytopes, ...
fig_num...
)

polytopes(1).vertices = [0 0; 5 0; 7, 0.5; 5 1; 0 1; 0 0];
polytopes(2).vertices = [6 0; 10 0; 10 1; 6 1; 8 0.5; 6 0];
polytopes = fcn_MapGen_fillPolytopeFieldsFromVertices(polytopes,1009,1);
fig_num = fig_num + 1;
[ ...
convex_hull_overlap_ratio,...
A_overlap,...
A_occupied...
] = ...
fcn_MapGen_calculateConvexHullOverlapRatio( ...
polytopes, ...
fig_num...
)
